### ISSUE TITLE
Still can't get this to work

### ISSUE THREAD

**Issue by joetriccas** [spdermn02/TouchPortal_ITunes_Plugin#11]
I'm so confused please help.

I really need this for streaming and I'm so close to just moving to something else lol

I have tried totally uninstalling Touch Portal, adding ALL of my playlists to my library (which downloaded all these songs to my phone *sadge*), reinstalling TP and the plug in.... Setting up all the things again... it just doesn't work. I touch the pause/play toggle button and it does nothing. NO errors in the logs or anything.

The only thing I notice is this:
12:14:22.502 - [ERROR] (Plugin Instance) pkg/prelude/bootstrap.js:1740
12:14:22.503 - [ERROR] (Plugin Instance)       throw error;
12:14:22.507 - [ERROR] (Plugin Instance)       ^
12:14:22.511 - [ERROR] (Plugin Instance) 
12:14:22.515 - [ERROR] (Plugin Instance) Error: The specified module could not be found.
12:14:22.519 - [ERROR] (Plugin Instance) 
12:14:22.523 - [ERROR] (Plugin Instance) C:\Users\joetr\AppData\Local\Temp\pkg\ee5c5aab670c7c4419c0933863c7417a4ced34b49a950f497ec216282240940a\winax\build\Release\node_activex.node
12:14:22.528 - [ERROR] (Plugin Instance)     at process.dlopen (pkg/prelude/bootstrap.js:2114:28)
12:14:22.533 - [ERROR] (Plugin Instance)     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
12:14:22.537 - [ERROR] (Plugin Instance)     at Module.load (node:internal/modules/cjs/loader:981:32)
12:14:22.541 - [ERROR] (Plugin Instance)     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
12:14:22.545 - [ERROR] (Plugin Instance)     at Module.require (node:internal/modules/cjs/loader:1005:19)
12:14:22.550 - [ERROR] (Plugin Instance)     at Module.require (pkg/prelude/bootstrap.js:1719:31)
12:14:22.554 - [ERROR] (Plugin Instance)     at require (node:internal/modules/cjs/helpers:102:18)
12:14:22.557 - [ERROR] (Plugin Instance)     at Object.<anonymous> (C:\snapshot\TouchPortal_ITunes_Plugin\node_modules\winax\activex.js:1:94)
12:14:22.562 - [ERROR] (Plugin Instance)     at Module._compile (pkg/prelude/bootstrap.js:1794:22)
12:14:22.568 - [ERROR] (Plugin Instance)     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
12:14:22.572 - [ERROR] (Plugin Instance)   code: 'ERR_DLOPEN_FAILED'
12:14:22.576 - [ERROR] (Plugin Instance) }

Which might be related to your plug in I'm not sure?

Anyways I'm gonna try to get this sorted one last time and if not will just look for another solution
[log.txt](https://github.com/spdermn02/TouchPortal_ITunes_Plugin/files/8890527/log.txt)
.

**Comment by spdermn02** [comment]
Sorry this didn't work first time. I literally use this plugin every day. (Still need to sort out the Library vs everything else issue though)

It looks like either a build I did was messed up and I didn't realize or something is not extracting that specific module correctly. 

I can try to do another build of the code for you and verify that module exists. And send it on over. 

Can you see if maybe a virus/anti-malware program isn't removing it?

**Comment by joetriccas** [comment]
I'm sorry I was a whingy boy in the last message Spdrmn - you;re doing awesome work and I know you have lots of plug ins to manage. What's weird is that the plug in has worked since you released this build, so it's very weird. 

I only have Windows Defender on so if a file is getting flagged it'll be a widespread issue I imagine so surprising no one else has reported?

**Comment by joetriccas** [comment]
The file definitely isn't there though:
![image](https://user-images.githubusercontent.com/85166160/173582965-a19599d9-1556-4eca-bfd0-29e928d58944.png)

**Comment by joetriccas** [comment]
I remember this file was present in the plugins install dir but for some reason isn;t making it to this temp location so I'll try manually copying it in and seeing if that resolves things.

**Comment by joetriccas** [comment]
Okay - pasting that file from 
C:\Users\joetr\AppData\Roaming\TouchPortal\plugins\TPiTunes\node_activex.node
to
C:\Users\joetr\AppData\Local\Temp\pkg\ee5c5aab670c7c4419c0933863c7417a4ced34b49a950f497ec216282240940a\winax\build\Release\
and restarting TouchPortal returns full functionality to the plug in.....

So something may be going wrong in installation? I'm unsue on the initialsation chain for this but that's my insight :D

**Comment by spdermn02** [comment]
Thank you for the kind words!

It definitely is odd that this happened. Another user had similar issue and yes copying the code there worked. But it shouldn't be required. I'll have to do some research when I have time. 

Feel free to leave any comments/issues/questions here or through the official Touch Portal discord #itunes channel.

**Comment by joetriccas** [comment]
Just to note I recently updated the Touch Portal client and the above issue was invoked by that update. It appears that updates to the client are clearing out certain files I'm not sure

**Comment by spdermn02** [comment]
it really doesn't make sense honestly.  This has worked for many others, but maybe i made a mistake in a build I'll have to do some research.

**Comment by spdermn02** [comment]
i know it's been a while but have you had any luck? I'll be releasing a new bug fix release shortly that fixes some issues -but this issue is still a mystery.

**Comment by joetriccas** [comment]
Howdy - I mean I know the exact reproduction steps if that helps?

From my perspective, every Touch Portal release the directory:
C:\Users\joetr\AppData\Local\Temp\pkg\ee5c5aab670c7c4419c0933863c7417a4ced34b49a950f497ec216282240940a\winax\build\Release

Is totally cleared out. This means when the plug in initialises it fails to find a dependency (the node binary) and dies. If I manually paste the file into the directory and restart Touch Portal, it works absolutely fine, until the next update.

This has been the case every Touch Portal release, since I first encountered this. Can't the plugin just look for the file in the actual plugin install dir rather than this other build folder? (apologies if that is a stupid question feel free not to answer it LUL)

**Comment by joetriccas** [comment]
I should also note I have a background including 13 years of software testing/automation and so I do simply break stuff by proximity

**Comment by joetriccas** [comment]
I'd not used Touch Portal in a good few weeks, just took update 3.1, build 12 and low and behold:
![image](https://user-images.githubusercontent.com/85166160/234370895-d9f21197-3b8c-4850-abfb-f895fd415831.png)

**Comment by spdermn02** [comment]
What's weird is an update to touch portal doesn't even know about that folder. Also I've updated with alpha builds as I help test future releases of touch portal and have never had that problem either. 

My expectation is it should look local as I include it local but apparently my assumption was incorrect. 

Still that folder shouldn't be touched by touch portal upon updates.

**Comment by joetriccas** [comment]
I wonder, could this be related to a path env variable or something like that? Ngl I'm clasping at straws here but it's so odd that it always defaults to this temp location for the node file. It is clearly something to do with my machine.

I have many dev tools installed, so potentially could be something to do with that? Eurgh sorry to be a problem child!

I'll see if the latest version improves things :D

**Comment by triccaj** [comment]
Hi just a heads up it turns out that I was inadvertently using my work github in the above and so this is actually my personal one

**Comment by triccaj** [comment]
So this may have been an issue in Touch Portal? For some reason I took a hiatus from streaming, have done a full WIndows reinstall since then, and now I have no issues,. Update TouchPortal, update the plug in, in true Steve Jobs style it 'just works'....

Love a heisenbug. Thanks for your continued commitment Spdermn02!!

**Comment by spdermn02** [comment]
I agree.. don't know exactly why some people have issues and others don't. Makes it difficult to pin point the cause. But glad it's working now!! Thanks for the kind words.
